name: Run Sonarqube scan

on:
  workflow_dispatch:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/sonarqube.yaml'
      - 'src/**'
      - 'tests/**'
  push:
    branches:
      - 'main'
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/sonarqube.yaml'
      - 'src/**'
      - 'tests/**'

jobs:
  scan-code:
    name: Scan Bridge code
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies for the tests
        run: pip install -r tests/dev-requirements.txt

      - name: Run tox
        run: tox -e py

      - name: Get coverage report
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.85
          thresholdNew: 0.9
          thresholdModified: 0.7

      - name: scan source code and tests on pull request
        if: github.event_name == 'pull_request'
        uses: sonarsource/sonarqube-scan-action@v5.3.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=sam-trino-bridge
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
            -Dsonar.python.version=3.12
            -Dsonar.tests=tests/
            -Dsonar.sources=src/
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_DEV_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_DEV_URL }}
          SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}


      - name: scan source code and tests on push
        if: github.event_name == 'push'
        uses: sonarsource/sonarqube-scan-action@v5.3.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=sam-trino-bridge
            -Dsonar.branch=${{ github.ref_name }}
            -Dsonar.scm.revision=${{ github.sha }}
            -Dsonar.python.version=3.12
            -Dsonar.tests=tests/
            -Dsonar.sources=src/
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_DEV_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_DEV_URL }}
          SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
